---
- name: remove distribution packages
  apt:
    name: "{{ packages }}"
    state: absent
    dpkg_options: 'force-confnew,force-confdef'
    autoclean: yes
    autoremove: yes
    update_cache: yes
    cache_valid_time: 3600
  vars:
    packages:
    - mongodb

- name: Add MongoDB key
  apt_key:
    url: "https://www.mongodb.org/static/pgp/server-{{ mongodb_version }}.asc"
    state: present

- name: install Debian MongoDB repo
  apt_repository:
    repo: "deb http://repo.mongodb.org/apt/debian {{ ansible_distribution_release }}/mongodb-org/{{ mongodb_version }} main"
    state: present
    filename: mongodb-org
  when: (ansible_distribution | lower) == "debian"

- name: install Ubuntu MongoDB repo
  apt_repository:
    repo: "deb [ arch=amd64 ] http://repo.mongodb.org/apt/ubuntu {{ ansible_distribution_release }}/mongodb-org/{{ mongodb_version }} multiverse"
    state: present
    filename: mongodb-org
  when: (ansible_distribution | lower) == "ubuntu"

- name: install MongoDB
  apt:
    name: "{{ packages }}"
    state: latest
    dpkg_options: 'force-confnew,force-confdef'
    autoclean: yes
    autoremove: yes
    update_cache: yes
  vars:
    packages:
    - mongodb-org

- name: start mongod daemon
  systemd:
    name: mongod
    state: started
    enabled: yes

...
